import os
import requests
import time
import threading
from flask import Flask

app = Flask(__name__)

# APNA TOKEN AUR CHAT ID YAHAN DAALEIN
TOKEN = '8613588573:AAHhrbzvG3DVPCbVZV2Bx1wUKAtpdJK1enk'
chat_id = '1179672183'

def get_syn_signal():
    try:
        # Coinpaprika API - Ekdam stable aur Render friendly (No 429, No DNS errors)
        url = "https://api.coinpaprika.com/v1/tickers/syn-synapse"
        headers = {'User-Agent': 'Mozilla/5.0'}
        response = requests.get(url, headers=headers, timeout=15)
        
        if response.status_code != 200:
            return f"API Error: Status {response.status_code}"
            
        data = response.json()
        
        # Data extraction from Coinpaprika
        quotes = data['quotes']['USD']
        price = quotes['price']
        change = quotes['percent_change_24h']
        
        # --- BUY / SELL ANALYSIS LOGIC ---
        signal = ""
        action_emoji = ""
        
        if change > 3.0:
            signal = "STRONG BUY 🚀 (Bullish Momentum)"
            action_emoji = "🟢"
        elif change > 0:
            signal = "BUY / HOLD 📈 (Market Up)"
            action_emoji = "🟢"
        elif change < -3.0:
            signal = "STRONG SELL ⚠️ (Bearish Drop)"
            action_emoji = "🔴"
        else:
            signal = "SELL / WAIT 📉 (Market Down)"
            action_emoji = "🔴"

        message = (
            f"🤖 *SYNAPSE (SYN) Live Signal*\n\n"
            f"{action_emoji} *Action:* {signal}\n"
            f"💰 *Current Price:* ${price:.4f}\n"
            f"📊 *24h Change:* {change:.2f}%\n\n"
            f"_Auto-generated by Render Bot_"
        )
        return message
    except Exception as e:
        return f"Error fetching analysis: {str(e)}"

def send_telegram():
    # Bot start hote hi pehla message turant bhej dega
    time.sleep(5) # Thoda wait taaki server fully boot ho jaye
    while True:
        message = get_syn_signal()
        tg_url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
        payload = {"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}
        try:
            requests.post(tg_url, json=payload, timeout=10)
        except:
            pass
        
        # Har 20 minute (1200 seconds) ka gap
        time.sleep(1200)

@app.route('/')
def home():
    return "Majbut Bot is running automatically in background!"

if __name__ == "__main__":
    # Background thread chalu karna jo bina trigger ke message bhejta rahega
    threading.Thread(target=send_telegram, daemon=True).start()
    
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port)
